Ads.Home.First: '<a href="#"><img class="img-responsive" src="/Planetjaipur/img/post/add/add1.jpg" alt=""></a>'
Ads.Home.Second: '<a href="#"><img class="img-responsive" src="/Planetjaipur/img/post/add/add2.jpg" alt=""></a>'
Ads.Sidebar.First: '<a href="#"><img class="img-responsive" src="/Planetjaipur/img/post/add/add3.jpg" alt=""></a>'
Ads.Sidebar.Second: '<a href="#"><img class="img-responsive" src="/Planetjaipur/img/post/add/add6.jpg" alt=""></a>'
Ads.Top: '<a href="#"><img class="img-responsive" src="/Planetjaipur/img/post/google-add.jpg" alt=""></a>'
Facebook.admins: '#'
fafadfadf: adfadsfadsf
Seo.og.type: article
Site.copyright: '© Copyrights reserved 2016, PlanetJaipur.com'
Site.email: info@planetjaipur.com
Site.Logo: 'http://128.199.234.133/planetjaipur/images/presets/preset1/logo.png'
Site.name: 'Planet Jaipur'
Site.Website: www.planetjaipur.com
testafad: adfadfadfasdf
Twitter.card: summary
Twitter.site: planetjaipur
wwwwfafadfadf: adfadsfadsf
